# Generated by Django 3.2.8 on 2021-10-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarriageRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brideName', models.CharField(blank=True, max_length=50, null=True)),
                ('bridesNid', models.CharField(blank=True, max_length=100, null=True)),
                ('bridesBirthCertificate', models.CharField(blank=True, max_length=100, null=True)),
                ('bridesPassport', models.CharField(blank=True, max_length=100, null=True)),
                ('bridesFathersname', models.CharField(blank=True, max_length=50, null=True)),
                ('bridesFathersNid', models.CharField(blank=True, max_length=50, null=True)),
                ('bridesMothersname', models.CharField(blank=True, max_length=50, null=True)),
                ('bridesMothersNid', models.CharField(blank=True, max_length=50, null=True)),
                ('bridesOccupation', models.CharField(blank=True, max_length=50, null=True)),
                ('bridesWorkplace', models.CharField(blank=True, max_length=50, null=True)),
                ('brideImages', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('brideSignature', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('groomsName', models.CharField(blank=True, max_length=50, null=True)),
                ('groomsNid', models.CharField(blank=True, max_length=100, null=True)),
                ('groomsBirthCertificate', models.CharField(blank=True, max_length=100, null=True)),
                ('groomsPassport', models.CharField(blank=True, max_length=100, null=True)),
                ('groomsFathersname', models.CharField(blank=True, max_length=50, null=True)),
                ('groomsFathersNid', models.CharField(blank=True, max_length=50, null=True)),
                ('groomsMothersname', models.CharField(blank=True, max_length=50, null=True)),
                ('groomsMothersNid', models.CharField(blank=True, max_length=50, null=True)),
                ('groomsOccupation', models.CharField(blank=True, max_length=50, null=True)),
                ('groomsWorkplace', models.CharField(blank=True, max_length=50, null=True)),
                ('groomImages', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('groomSignature', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('firstAttestor', models.CharField(blank=True, max_length=50, null=True)),
                ('firstAttestorNid', models.CharField(blank=True, max_length=50, null=True)),
                ('secondAttestor', models.CharField(blank=True, max_length=50, null=True)),
                ('secondAttestorNid', models.CharField(blank=True, max_length=50, null=True)),
                ('thirdAttestor', models.CharField(blank=True, max_length=50, null=True)),
                ('thirdAttestorNid', models.CharField(blank=True, max_length=50, null=True)),
                ('marrige_place', models.CharField(blank=True, max_length=50, null=True)),
                ('marriage_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
