# Generated by Django 3.2.8 on 2021-10-11 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_marriageregister_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marriageregister',
            name='user',
        ),
    ]
