# Generated by Django 3.2.8 on 2021-10-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_remove_marriageregister_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='marriageregister',
            name='serialNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marriageregister',
            name='marriage_date',
            field=models.DateTimeField(),
        ),
    ]
