# Generated by Django 3.2.8 on 2021-10-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_auto_20211016_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marriageregister',
            name='serialNo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
