# Generated by Django 3.2.8 on 2022-01-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_alter_marriageregister_serialno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marriageregister',
            name='brideImages',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='marriageregister',
            name='brideSignature',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='marriageregister',
            name='groomImages',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='marriageregister',
            name='groomSignature',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
