# Generated by Django 3.2.8 on 2022-02-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0006_auto_20220118_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='marriageregister',
            name='brideMobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='marriageregister',
            name='groomMobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
