# Generated by Django 3.2.8 on 2022-02-18 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0007_auto_20220218_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marriageregister',
            old_name='brideMobile',
            new_name='bridemobile',
        ),
        migrations.RenameField(
            model_name='marriageregister',
            old_name='groomMobile',
            new_name='groommobile',
        ),
    ]
